version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deployscripts/before_deploy.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deployscripts/after_deploy.sh
      timeout: 300
      runas: root
